FROM postgres:16.1

# Install necessary packages
RUN apt-get update && apt-get install -y \
    git \
    postgresql-server-dev-16 \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Clone and install pgvector
# Clone and install pgvector
RUN cd /tmp \
    && git clone --branch v0.7.2 https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make \
    && make install \
    && rm -rf /tmp/pgvector