#!/bin/bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export OPENAI_API_KEY="your_openai_api_key"
export POSTGRESQL_HOST="postgres_container"
export POSTGRESQL_PORT=5432
export POSTGRESQL_DATABASE="vector_db"
export POSTGRESQL_USER="alex"
export POSTGRESQL_PASSWORD="alexPostgresPassword"
export GPT_MODEL='gpt-4o'
export GPT_EMBEDDING_ENGINE='text-embedding-3-large'

# Function to install Miniconda
install_miniconda() {
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O Miniconda3-latest-Linux-x86_64.sh
    bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
    rm Miniconda3-latest-Linux-x86_64.sh
    export PATH="$HOME/miniconda/bin:$PATH"
    conda init
}

# Function to create and activate Conda environment
setup_conda_env() {
    conda create -y -n ray_env python=3.10
    source $HOME/miniconda/etc/profile.d/conda.sh
    conda activate ray_env
    pip install ray[serve]==2.31.0 
    pip install fastapi requests
    pip install mlflow==2.14.2
    pip install psycopg2==2.9.5
    pip install pytest==8.2.2
    pip install pyzmq==26.0.3
    pip install python-dotenv==1.0.1
    pip install fuzzywuzzy==0.18.0 
    pip install python-Levenshtein==0.25.1
    pip install nltk==3.8.1
    pip install openai==1.35.10
    pip install spacy==3.7.5
    pip install tiktoken==0.7.0
    pip install tenacity==8.5.0
    pip install PyMuPDF==1.24.7
    pip install pyautogen==0.2.32
    pip install chromadb==0.5.4
    pip install markdownify==0.13.1
    pip install pypdf==4.3.0
    pip install gradio==4.38.1
    pip install IPython
}

# Function to install Prometheus and Grafana
install_prometheus_grafana() {
    # Install Prometheus
    wget https://github.com/prometheus/prometheus/releases/download/v2.31.0/prometheus-2.31.0.linux-amd64.tar.gz
    tar -xvf prometheus-2.31.0.linux-amd64.tar.gz
    mv prometheus-2.31.0.linux-amd64 /etc/prometheus
    rm prometheus-2.31.0.linux-amd64.tar.gz

    # Install Grafana
    wget https://dl.grafana.com/oss/release/grafana-8.3.0.linux-amd64.tar.gz
    tar -xvf grafana-8.3.0.linux-amd64.tar.gz
    mv grafana-8.3.0 /usr/share/grafana
    rm grafana-8.3.0.linux-amd64.tar.gz
}

# Install Miniconda if not already installed
if [ ! -d "$HOME/miniconda" ]; then
    install_miniconda
fi

# Create and activate Conda environment
source $HOME/miniconda/etc/profile.d/conda.sh
if ! conda info --envs | grep -q "ray_env"; then
    setup_conda_env
else
    conda activate ray_env
fi

# Install Prometheus and Grafana if not already installed
if [ ! -d "/etc/prometheus" ] || [ ! -d "/usr/share/grafana" ]; then
    install_prometheus_grafana
fi

export RAY_GRAFANA_HOST="http://127.0.0.1:3000"

# Run Ray command based on the mode
if [ "$1" = "head" ]; then
    ray start --head --dashboard-host 0.0.0.0 --metrics-export-port=8080 --num-cpus=12
elif [ "$1" = "worker" ]; then
    ray start --address=$RAY_HEAD_IP:6379 --metrics-export-port=8080 --num-cpus=12
else
    exec "$@"
fi

# Give Ray some time to start and generate the necessary files
sleep 20

# Start Prometheus and Grafana using the configuration files generated by Ray
start_prometheus_grafana() {
    PROMETHEUS_CONFIG="/tmp/ray/session_latest/metrics/prometheus/prometheus.yml"
    GRAFANA_CONFIG="/tmp/ray/session_latest/metrics/grafana/grafana.ini"
    GRAFANA_PROVISIONING="/tmp/ray/session_latest/metrics/grafana/provisioning"

    if [ -f "$PROMETHEUS_CONFIG" ]; then
        /etc/prometheus/prometheus --config.file=$PROMETHEUS_CONFIG &
    else
        echo "Prometheus config file not found: $PROMETHEUS_CONFIG"
    fi

    if [ -f "$GRAFANA_CONFIG" ]; then
        if [ -d "$GRAFANA_PROVISIONING" ]; then
            /usr/share/grafana/bin/grafana-server --config $GRAFANA_CONFIG --homepath /usr/share/grafana/ &
        else
            echo "Grafana provisioning directory not found: $GRAFANA_PROVISIONING"
        fi
    else
        echo "Grafana config file not found: $GRAFANA_CONFIG"
    fi
}

# Start Prometheus and Grafana
start_prometheus_grafana

# Keep the container running
tail -f /dev/null
