version: '3.7'

services:
  ray-head:
    build: ./ray
    container_name: ray-head
    ports:
      - "8265:8265"   # Ray dashboard
      - "3000:3000"   # Custom port
      - "10001:10001" # Custom port
      - "8000:8000"   # Custom port
      - "6379:6379"   # Redis default port
      - "6380:6380"   # Redis default port
      - "6381:6381"   # Redis default port
      - "12345:12345" # Ray gRPC port (head node)
      - "12346:12346" # Ray gRPC port (worker node)
      - "8001:8001"   # Custom port
      - "8076:8076"   # Custom port
    command: ["head"]
    shm_size: '8g'
    environment:
      - RAY_HEAD_IP=ray-head
      - RAY_DISABLE_DOCKER_CPU_WARNING=1
    volumes:
      - ray_data:/root/ray
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '8g'
        reservations:
          cpus: '1.0'
          memory: '4g'

volumes:
  ray_data:
    driver: local
